user_input=input("Enter text to write the file: ")
print("Data successfully written to output.txt.")
file2=open("output.txt",'w')
file2.write(user_input + "\n")
file2.close()
additional_input = input("Enter additional text to append: ")
print("Data successfully appended.")
file2=open("output.txt",'a')
file2.write(additional_input +"\n")
file2.close()
print("Final content of output.txt: ")
file2=open("output.txt",'r')
reading_file=file2.read()
print(reading_file)
file2.close()
